version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db :
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: xyz_multifinance
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3307:3306"
